apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chatapp
type: Opaque
data:
  JWT_SECRET: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjMk5qVTJOREkzTlN3aWFXRjBJam94TnpZMk5UWTBNamMxZlEuWUE4SmF5dFZ5d1NUeHVOa2tIZ2JmeURCOU9JM3ducVU5c3JnRmFHN2lUOA==